using System.ComponentModel;

namespace EntitiesPOJO {
    public enum EntityTypes {
        [Description("EXCEPTIONS")] ApplicationMessage,
        [Description("PAYMENT_METHODS")] PaymentMethod,
        [Description("TRANSACTIONS")] Transaction,
        [Description("ORDERS_TRANSACTIONS")] OrdersTransactions,
        [Description("CATEGORIES")] Category,
        [Description("USERS_CATEGORIES")] UsersCategories,
        [Description("STORES_CATEGORIES")] StoresCategories,
        [Description("PRODUCTS_CATEGORIES")] ProductsCategories,
        [Description("PRODUCT_REQUESTS_CATEGORIES")] ProductRequestsCategories,
        [Description("USERS")] Users,
        [Description("CODES ")] Currency,
        [Description("STORE")] Store,
        [Description("SHIPPING_PROVIDER")] ShippingProvider,
        [Description("COUPONS")] Coupon,
        [Description("PRODUCT_PROVIDERS")] ProductProvider,
        [Description("SHIPPING_METHODS")] ShippingMethods,
        [Description("USER_CONTACTS")] UserContacts,
        [Description("PRODUCTS")] Product,
        [Description("ROLES")] Role,
        [Description("CUSTOMER_SERVICE_TYPES")] CustomerServiceType,
        [Description("CUSTOMER_SERVICE_REQUESTS")] CustomerServiceRequest,
        [Description("OPTION_LISTS")] OptionList,
        [Description("USER_LOCATIONS")] UserLocation,
        [Description("USERS_ROLES_VIEWS")]UserRoleView,
        [Description("VIEWS")] View,
        [Description("PRODUCT_MEDIA")] ProductMedia,
        [Description("USERS_STORES")] UsersStores,
        [Description("USERS_SHIPPING_PROVIDERS")] UsersShippingProviders,
        [Description("PRODUCT_REQUESTS")] ProductRequest,
        [Description("INVENTORY")] Inventory,
        [Description("USERS")] Customer,
        [Description("SHOPPING_CART")] ShoppingCart,
        [Description("PRODUCT_REQUEST_RESPONSES")] ProductRequestResponses,
        [Description("INTERNAL_ACCOUNTS")] InternalAccount,
        [Description("USERS_MEDIA")] UserMedia,
        [Description("ORDERS")] Orders,
        [Description("ORDERS_PRODUCTS")] OrdersProducts,
        [Description("ORDERS_PRODUCTS_INVENTORY")] OrdersProductsInventory,
        [Description("ORDERS_STATUS")] OrdersStatus
    }
}